-- @description Modulation Box
-- @version 1.0.3
-- @author Tadej Supukovic (tdspk)
-- @provides
--   tdspk - Modulation Box - Common Functions.lua
--   [main] tdspk - Modulation Box - Copy ACS settings from last touched FX parameter.lua
--   [main] tdspk - Modulation Box - Copy LFO Settings from last touched FX parameter.lua
--   [main] tdspk - Modulation Box - Enable ACS for last touched FX parameter.lua
--   [main] tdspk - Modulation Box - Enable LFO for last touched FX parameter.lua
--   tdspk - Modulation Box - Info Panel.lua
--   [main] tdspk - Modulation Box - Link last touched FX parameter to link parent.lua
--   tdspk - Modulation Box - List View.lua
--   [main] tdspk - Modulation Box - Paste ACS settings.lua
--   [main] tdspk - Modulation Box - Paste LFO settings.lua
--   [main] tdspk - Modulation Box - Set last touched FX parameter as link parent and auto-link following touched FX parameters (background).lua
--   [main] tdspk - Modulation Box - Set last touched FX parameter as link parent.lua
--   [main] tdspk - Modulation Box - Show knobs for each modulated FX parameter in TCP.lua
--   [main] tdspk - Modulation Box - Toggle TCP Knob Visibility When Adding Modulators.lua
--   [main] tdspk - Modulation Box - Unlink last touched parameter.lua
-- @changelog
--   Support for FX Containers
--   Added support for tcp toggle
--   First version